### ISSUE TITLE
Field size limits

### ISSUE THREAD

**Issue by docelic** [j8r/crystalizer#10]
For example, at least in ByteFormat, there is currently no way to set the maximum size of bytes to read for a field when doing deserialization.

So if crystalizer is reading from an IO, someone passing a long string without a `@byte_delimiter` char in it can make crystalizer consume IO endlessly.

I guess we should use the existing annotations model to be able to set max length on all fields.

(Note: because this would be implemented via annotations, it would be a compile-time, maximum limit.
The next-level improvement to this, which would be support for size-dependent field deserialization in runtime, is not part of this issue.)

**Comment by j8r** [comment]
It can't be done, because how do you know when the string ends? A delimiter is still needed, somehow. I thought about a byte size annotation, but it can only be used to describe the exact length in bytes of the field.

**Comment by j8r** [comment]
As talked in the Crystal chat, we can implement this for a conformance/security point of view. Protocols can have string fields with a fixed size.

**Comment by docelic** [comment]
Hello,

Just checking the state on this issue.

In a project I am working on (using `ByteFormat`), there is a requirement to deserialize strings, but to limit their maximum size.

Something like:

```
struct A
  getter x : UInt32

  @[Crystalizer::Field(max_length: 12)]
  getter y : String
end
```

This would then try to read a string into `y` (string terminated by `@byte_delimiter`), but not more than 12 characters of total length.

If the max length is exceeded, it should fail the deserialization.

Is there any likelyhood of that getting implemented?
I checked the sources for ByteFormat deserialization for Strings:

```
  # Deserializes a `String` from reading from the `io`, delimited by a trailing `byte_delimiter`.
  def deserialize(to type : String.class)
    String.build do |str|
      while (byte = @io.read_byte) && byte != @byte_delimiter
        str.write_byte byte
      end
    end
  end
```

It doesn't seem it'd be too hard to add a counter in there as well.

**Comment by docelic** [comment]
By the way, shouldn't strings be deserialized with something like:
https://crystal-lang.org/api/1.1.1/IO.html#gets(delimiter:Char,limit:Int,chomp=false):String?-instance-method

Rather than doing manual `read_byte`s? This would still honor the delimiter thing and be able to set max length in one go, plus it could maybe be more correct when the input is UTF?

**Comment by j8r** [comment]
I guess you're right. PRs welcomed 😄

**Comment by j8r** [comment]
I'd just keep the same naming. We may change the delimiter from `Byte` to `Char`, it is more logical for Crystal strings (we can call it string_delimiter).

**Comment by docelic** [comment]
Hey @j8r, the part which I am wondering about is how do you want to expose annotations to individual properties.

I am looking at the code from the end of `src/byte_format/deserialize.cr`. This is the code for deserialization. Variable `variable` is present there and we could access its annotations via `#annotations`. But when the code calls deserialize:

```
  deserialize variable.type
```

Evidently only `variable.type` is passed (not `variable` itself) and so there is no way to retrieve the annotations from the deserialize function.

How would you redesign the code to make this possible? This is needed both for this issue and for #13, and probably for all other more complex features that we would add later.

**Comment by j8r** [comment]
This can be arguments to the deserialize method. The length limit won't make sense for integers and float for example.
Also having arguments allows to test the method in the specs easily.

**Comment by docelic** [comment]
Ah yes, just adding more overloads. OK, sounds good I will try that, thanks.
