### ISSUE TITLE
Size-dependent reads

### ISSUE THREAD

**Issue by docelic** [j8r/crystalizer#13]
Opening this ticket in advance of actual work. I am serializing/deserializing structures which contain strings, and some of those strings are not terminated by \0, but their size (without \0) is specified in a separate field.

I.e. instead of:

```cr
string = "test\0"
```

they have:

```cr
len = 4
string = "test"
```

Support for this should be added. I will work on #10 first and then we can see what to do about this one.

Thanks!

**Comment by j8r** [comment]
Agreed. Indeed if the field size is specified, the delimiter won't be taken into account.

**Comment by j8r** [comment]
Thus, it duplicates #10 in a sense because implied by it.

**Comment by docelic** [comment]
I believe they are separate issues.

In #10, when we make it work, we will have a new annotation `max_length`, which defines the max possible length, defined at compile time. So the deserializer will be searching for `char_delimiter` OR `max_length` of bytes read. The `max_length` here will be just a protection from uncontrolled reads -- if the code hits `max_length`, it's certain that there is an error (because \0 wasn't found).

And in the case of #13 here, this is for runtime (de)serialization of strings which are not terminated by \0, but their size is specified in a separate field. The interface for this will look something like:

```cr
struct A
  getter x : UInt32

  @[Crystalizer::Field(length_from: x)]
  getter y : String
end

A.new(5, "hello") # Notice no \0, just "hello".size == 5
A.new(8, "hello wo") # Notice no \0, just "hello wo".size == 8
```


And then the code for deserialization will, instead of calling `gets`, call `read_string`:

```cr
@io.read_string( bytesize: x )
```

(And for serializing, it will be populating `x = y.bytesize`, and not appending \0 at the end.)

**Comment by j8r** [comment]
Right, but we could still combine both into one annotation. Got an idea, we can something a bit more original as an annotation: `length: [2..4]`, `length: [..4]` etc. If the type is an integer, then discard the byte delimiter.

**Comment by j8r** [comment]
Right, but we could still combine both into one annotation. Got an idea, we can have something a bit more original as an annotation: `length: [2..4]`, `length: [..4]`, `length: 5` etc. If the type is an integer, then discard the byte delimiter.

**Comment by j8r** [comment]
What I think is it will be better to have a way to specify how a type is (de)serialized. This way, one could achieve what you describe here easily.

**Comment by docelic** [comment]
OK sounds good, I will try to see how they provide a generic feature for that in Crystal for JSON/YAML.

**Comment by docelic** [comment]
Could you show some pseudo code for:

> What I think, which could be included in this library, is a type which provides this functionality, instead of an annotation.
> What we need is an interface, i.e. module/abstract struct - that's essentially it.

It'd help me start. Thanks.

**Comment by j8r** [comment]
I can do it this week-end, would be simpler. It is not hard to do. It will be a bit like `Crystalizer::Any`, plus abstract methods, which is included in `Crystalizer::JSON::Any` and `Crystalizer::YAML::Any`

**Comment by docelic** [comment]
Great, by all means please do if you could since I am counting on this for a real/ongoing project. Thanks!

**Comment by j8r** [comment]
I'll rework the API to make the serializers/deserializer consitent.
Do we prefer passing a builder/parser/io around along with class methods, or having to instantiate an object with the builder/parser/io as an instance variable?

**Comment by j8r** [comment]
Personally, I prefer the OOP approach more. Then, the JSON and YAML API will change to be more like the `ByteFormat` one.

This change is necessary be able to have custom deserialization/serialization for an object.
